# Generated by Django 6.0.6 on 2026-06-30 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("excel", "Excel上传接口"), ("dock", "系统对接接口")],
                        max_length=10,
                        verbose_name="数据来源",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                ("sheet_count", models.IntegerField(verbose_name="工作表数量")),
                ("total_rows", models.IntegerField(verbose_name="总数据行数")),
                (
                    "validation_passed",
                    models.BooleanField(default=False, verbose_name="校验通过"),
                ),
                (
                    "validation_errors",
                    models.JSONField(blank=True, default=list, verbose_name="校验错误"),
                ),
                (
                    "validation_warnings",
                    models.JSONField(blank=True, default=list, verbose_name="校验警告"),
                ),
                (
                    "validation_detail",
                    models.JSONField(blank=True, default=dict, verbose_name="校验明细"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                ("review_notes", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "dw_sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("syncing", "同步中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="DataWorks同步",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_uploads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "upload_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
            ],
            options={
                "verbose_name": "上传记录",
                "verbose_name_plural": "上传记录",
                "db_table": "ifrs17_upload_record",
                "ordering": ["-upload_time"],
                "permissions": [
                    ("can_upload", "可以上传数据"),
                    ("can_review", "可以审核上传"),
                    ("can_view_all", "可以查看所有数据"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataWorksSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("syncing", "同步中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="目标表名"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "upload_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dw_sync_log",
                        to="data_input.uploadrecord",
                        verbose_name="关联上传记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "DataWorks同步日志",
                "verbose_name_plural": "DataWorks同步日志",
                "db_table": "ifrs17_dw_sync_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SheetData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("excel", "Excel上传接口"), ("dock", "系统对接接口")],
                        max_length=10,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(max_length=100, verbose_name="工作表名称"),
                ),
                ("headers", models.JSONField(default=list, verbose_name="表头")),
                ("rows", models.JSONField(default=list, verbose_name="数据行")),
                ("row_count", models.IntegerField(default=0, verbose_name="行数")),
                (
                    "display_cols",
                    models.IntegerField(default=0, verbose_name="显示列数"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="当前有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "upload_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheets",
                        to="data_input.uploadrecord",
                        verbose_name="所属上传记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作表数据",
                "verbose_name_plural": "工作表数据",
                "db_table": "ifrs17_sheet_data",
                "ordering": ["source", "sheet_name"],
                "indexes": [
                    models.Index(
                        fields=["source", "sheet_name", "-created_at"],
                        name="ifrs17_shee_source_039613_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="ifrs17_shee_is_acti_282a70_idx"
                    ),
                ],
            },
        ),
    ]
