# Generated by Django 6.0.6 on 2026-08-17 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_input", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="版本名称")),
                ("description", models.TextField(blank=True, verbose_name="版本说明")),
                (
                    "scenario_count",
                    models.IntegerField(default=0, verbose_name="情景数量"),
                ),
                (
                    "scenarios",
                    models.JSONField(blank=True, default=list, verbose_name="包含情景"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calc_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "计算版本",
                "verbose_name_plural": "计算版本",
                "db_table": "ifrs17_calc_version",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalculationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(max_length=40, verbose_name="情景")),
                (
                    "result_json",
                    models.JSONField(default=dict, verbose_name="结果数据"),
                ),
                (
                    "row_counts",
                    models.JSONField(blank=True, default=dict, verbose_name="行数统计"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="data_input.calculationversion",
                        verbose_name="所属版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "计算结果快照",
                "verbose_name_plural": "计算结果快照",
                "db_table": "ifrs17_calc_snapshot",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["version", "scenario"],
                        name="ifrs17_calc_version_38ded8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="用户名快照"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="操作类型"
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="操作名称"
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="操作对象"
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="操作详情")),
                (
                    "level",
                    models.CharField(
                        choices=[("INFO", "信息"), ("WARN", "警告"), ("ERROR", "错误")],
                        default="INFO",
                        max_length=10,
                        verbose_name="级别",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="来源IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="op_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统运行日志",
                "verbose_name_plural": "系统运行日志",
                "db_table": "ifrs17_system_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="ifrs17_syst_created_14e6c2_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="ifrs17_syst_action_6b9371_idx",
                    ),
                    models.Index(
                        fields=["level", "-created_at"],
                        name="ifrs17_syst_level_e5aafe_idx",
                    ),
                ],
            },
        ),
    ]
