# Generated by Django 6.0.6 on 2026-08-18 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_input", "0002_calculationversion_calculationsnapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutputFinancialStatementMtd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(max_length=40, verbose_name="情景")),
                ("row_idx", models.IntegerField(default=0, verbose_name="行序号")),
                ("row_json", models.JSONField(default=dict, verbose_name="行数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_input.calculationversion",
                        verbose_name="所属版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "输出财务报表_MTD",
                "verbose_name_plural": "输出财务报表_MTD",
                "db_table": "financial_statement_mtd",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["version", "scenario"],
                        name="financial_s_version_ce27f8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutputFinancialStatementYtd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(max_length=40, verbose_name="情景")),
                ("row_idx", models.IntegerField(default=0, verbose_name="行序号")),
                ("row_json", models.JSONField(default=dict, verbose_name="行数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_input.calculationversion",
                        verbose_name="所属版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "输出财务报表_YTD",
                "verbose_name_plural": "输出财务报表_YTD",
                "db_table": "financial_statement_ytd",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["version", "scenario"],
                        name="financial_s_version_81e3e9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutputPaaExistingBusinessOrganized",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(max_length=40, verbose_name="情景")),
                ("row_idx", models.IntegerField(default=0, verbose_name="行序号")),
                ("row_json", models.JSONField(default=dict, verbose_name="行数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_input.calculationversion",
                        verbose_name="所属版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "PAA计算_现有业务整理",
                "verbose_name_plural": "PAA计算_现有业务整理",
                "db_table": "paa_existing_business_organized",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["version", "scenario"],
                        name="paa_existin_version_08aa56_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutputPaaMtd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(max_length=40, verbose_name="情景")),
                ("row_idx", models.IntegerField(default=0, verbose_name="行序号")),
                ("row_json", models.JSONField(default=dict, verbose_name="行数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_input.calculationversion",
                        verbose_name="所属版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "PAA计算_MTD",
                "verbose_name_plural": "PAA计算_MTD",
                "db_table": "paa_mtd",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["version", "scenario"],
                        name="paa_mtd_version_38ecfc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutputPaaNewBusinessOrganized",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(max_length=40, verbose_name="情景")),
                ("row_idx", models.IntegerField(default=0, verbose_name="行序号")),
                ("row_json", models.JSONField(default=dict, verbose_name="行数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_input.calculationversion",
                        verbose_name="所属版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "PAA计算_新业务整理",
                "verbose_name_plural": "PAA计算_新业务整理",
                "db_table": "paa_new_business_organized",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["version", "scenario"],
                        name="paa_new_bus_version_4b859d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutputPaaSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(max_length=40, verbose_name="情景")),
                ("row_idx", models.IntegerField(default=0, verbose_name="行序号")),
                ("row_json", models.JSONField(default=dict, verbose_name="行数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_input.calculationversion",
                        verbose_name="所属版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "PAA计算_汇总",
                "verbose_name_plural": "PAA计算_汇总",
                "db_table": "paa_summary",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["version", "scenario"],
                        name="paa_summary_version_00fb44_idx",
                    )
                ],
            },
        ),
    ]
