# Generated by Django 6.0.6 on 2026-08-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_input", "0004_outputfinancialstatementmtd_balance_sheet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outputfinancialstatementmtd",
            name="row_json",
        ),
        migrations.RemoveField(
            model_name="outputfinancialstatementytd",
            name="row_json",
        ),
        migrations.RemoveField(
            model_name="outputpaaexistingbusinessorganized",
            name="row_json",
        ),
        migrations.RemoveField(
            model_name="outputpaamtd",
            name="row_json",
        ),
        migrations.RemoveField(
            model_name="outputpaanewbusinessorganized",
            name="row_json",
        ),
        migrations.RemoveField(
            model_name="outputpaasummary",
            name="row_json",
        ),
    ]
