# Generated by Django 6.0.6 on 2026-08-18 10:53

from django.db import migrations, models


def _safe_remove_stale_indexes(apps, schema_editor):
    """原 0006 直接 RemoveIndex 在本地 SQLite（索引从未创建）会报 no such index；
    此处改用原生 SQL 按索引名「存在才删除」，使迁移在本地库与生产库均可安全执行。"""
    from django.db import connection

    targets = [
        ("outputfinancialstatementmtd", "financial_s_version_ce27f8_idx"),
        ("outputfinancialstatementytd", "financial_s_version_81e3e9_idx"),
        ("outputpaamtd", "paa_mtd_version_38ecfc_idx"),
    ]
    with connection.cursor() as cur:
        if connection.vendor == "sqlite":
            for table, index_name in targets:
                cur.execute(
                    "SELECT 1 FROM sqlite_master WHERE type='index' AND name=%s",
                    [index_name],
                )
                if cur.fetchone():
                    cur.execute(f'DROP INDEX IF EXISTS "{index_name}"')
        else:  # mysql
            for table, index_name in targets:
                cur.execute(
                    f"SELECT 1 FROM information_schema.statistics "
                    f"WHERE table_schema=DATABASE() AND index_name=%s LIMIT 1",
                    [index_name],
                )
                if cur.fetchone():
                    cur.execute(f"DROP INDEX `{index_name}` ON `{table}`")


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("data_input", "0005_remove_outputfinancialstatementmtd_row_json_and_more"),
    ]

    operations = [
        migrations.RunPython(_safe_remove_stale_indexes, _noop_reverse),
        migrations.AddField(
            model_name="outputfinancialstatementmtd",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=26,
                null=True,
                verbose_name="数值",
            ),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementmtd",
            name="indent",
            field=models.IntegerField(default=0, verbose_name="缩进层级"),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementmtd",
            name="is_total",
            field=models.BooleanField(default=False, verbose_name="是否合计行"),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementmtd",
            name="item",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="科目名称"
            ),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementmtd",
            name="line_idx",
            field=models.IntegerField(default=0, verbose_name="科目行序"),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementmtd",
            name="period_date",
            field=models.DateField(blank=True, null=True, verbose_name="期间"),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementmtd",
            name="period_idx",
            field=models.IntegerField(default=0, verbose_name="期间序号"),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementmtd",
            name="statement_type",
            field=models.CharField(
                default="income_statement",
                help_text="balance_sheet=资产负债表；income_statement=利润表",
                max_length=20,
                verbose_name="报表类型",
            ),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementytd",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=26,
                null=True,
                verbose_name="数值",
            ),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementytd",
            name="indent",
            field=models.IntegerField(default=0, verbose_name="缩进层级"),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementytd",
            name="is_total",
            field=models.BooleanField(default=False, verbose_name="是否合计行"),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementytd",
            name="item",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="科目名称"
            ),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementytd",
            name="line_idx",
            field=models.IntegerField(default=0, verbose_name="科目行序"),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementytd",
            name="period_date",
            field=models.DateField(blank=True, null=True, verbose_name="期间"),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementytd",
            name="period_idx",
            field=models.IntegerField(default=0, verbose_name="期间序号"),
        ),
        migrations.AddField(
            model_name="outputfinancialstatementytd",
            name="statement_type",
            field=models.CharField(
                default="income_statement",
                help_text="balance_sheet=资产负债表；income_statement=利润表",
                max_length=20,
                verbose_name="报表类型",
            ),
        ),
        migrations.AddField(
            model_name="outputpaamtd",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=26,
                null=True,
                verbose_name="数值",
            ),
        ),
        migrations.AddField(
            model_name="outputpaamtd",
            name="indent",
            field=models.IntegerField(default=0, verbose_name="缩进层级"),
        ),
        migrations.AddField(
            model_name="outputpaamtd",
            name="is_total",
            field=models.BooleanField(default=False, verbose_name="是否合计行"),
        ),
        migrations.AddField(
            model_name="outputpaamtd",
            name="item",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="科目名称"
            ),
        ),
        migrations.AddField(
            model_name="outputpaamtd",
            name="line_idx",
            field=models.IntegerField(default=0, verbose_name="科目行序"),
        ),
        migrations.AddField(
            model_name="outputpaamtd",
            name="period_date",
            field=models.DateField(blank=True, null=True, verbose_name="期间"),
        ),
        migrations.AddField(
            model_name="outputpaamtd",
            name="period_idx",
            field=models.IntegerField(default=0, verbose_name="期间序号"),
        ),
        migrations.AddField(
            model_name="outputpaamtd",
            name="statement_type",
            field=models.CharField(
                default="income_statement",
                help_text="balance_sheet=资产负债表；income_statement=利润表",
                max_length=20,
                verbose_name="报表类型",
            ),
        ),
        migrations.AddIndex(
            model_name="outputfinancialstatementmtd",
            index=models.Index(
                fields=["version", "scenario", "statement_type"],
                name="financial_s_version_a14a38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outputfinancialstatementmtd",
            index=models.Index(
                fields=["version", "scenario", "statement_type", "period_date"],
                name="financial_s_version_811393_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outputfinancialstatementytd",
            index=models.Index(
                fields=["version", "scenario", "statement_type"],
                name="financial_s_version_99f027_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outputfinancialstatementytd",
            index=models.Index(
                fields=["version", "scenario", "statement_type", "period_date"],
                name="financial_s_version_1f6d3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outputpaamtd",
            index=models.Index(
                fields=["version", "scenario", "statement_type"],
                name="paa_mtd_version_895305_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outputpaamtd",
            index=models.Index(
                fields=["version", "scenario", "statement_type", "period_date"],
                name="paa_mtd_version_9ce471_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="outputfinancialstatementmtd",
            name="balance_sheet",
        ),
        migrations.RemoveField(
            model_name="outputfinancialstatementmtd",
            name="income_statement",
        ),
        migrations.RemoveField(
            model_name="outputfinancialstatementmtd",
            name="row_idx",
        ),
        migrations.RemoveField(
            model_name="outputfinancialstatementytd",
            name="balance_sheet",
        ),
        migrations.RemoveField(
            model_name="outputfinancialstatementytd",
            name="income_statement",
        ),
        migrations.RemoveField(
            model_name="outputfinancialstatementytd",
            name="row_idx",
        ),
        migrations.RemoveField(
            model_name="outputpaamtd",
            name="balance_sheet",
        ),
        migrations.RemoveField(
            model_name="outputpaamtd",
            name="income_statement",
        ),
        migrations.RemoveField(
            model_name="outputpaamtd",
            name="row_idx",
        ),
    ]
